# Generated by Django 5.2.7 on 2025-12-16 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_alter_cliente_email_alter_cliente_telefono_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=4, null=True)),
                ('calle', models.CharField(blank=True, max_length=15, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=25, null=True)),
                ('barrio', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=35, null=True)),
                ('localidad', models.CharField(blank=True, max_length=35, null=True)),
                ('nomenclatura_catastral', models.CharField(blank=True, max_length=20, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=100)),
                ('tipo_trabajo', models.CharField(choices=[('levantamiento_planimetrico', 'Levantamiento planimétrico'), ('levantamiento_altimetrico', 'Levantamiento altimétrico'), ('levantamiento_topografico_integral', 'Levantamiento topográfico integral'), ('levantamiento_gps_gnss', 'Levantamiento con GPS/GNSS'), ('levantamiento_drones', 'Levantamiento con drones/UAV'), ('levantamiento_estacion_total', 'Levantamiento con estación total'), ('mensura_urbana', 'Mensura de parcelas urbanas'), ('mensura_rural', 'Mensura de parcelas rurales'), ('subdivision_loteos', 'Subdivisión de terrenos'), ('unificacion_parcelas', 'Unificación de parcelas'), ('relevamiento_limites', 'Relevamiento de límites'), ('actualizacion_catastral', 'Actualización catastral'), ('determinacion_areas', 'Determinación de superficies'), ('nivelacion_obras', 'Nivelación de obras'), ('trazado_replanteo', 'Trazado y replanteo'), ('control_deformaciones', 'Control de deformaciones'), ('levantamiento_as_built', 'Levantamiento As-built')], max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='clientes.cliente')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trabajos.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='planos/')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='trabajos.trabajo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='trabajos.ubicacion')),
            ],
        ),
    ]
