# Generated by Django 5.2.7 on 2025-10-23 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_estado_cliente_activo_remove_cliente_apellido_and_more'),
        ('trabajos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='planos/'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='titulo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='trabajos.ubicacion'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='trabajos.trabajo'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='trabajos.trabajo'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='trabajos.ubicacion'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='clientes.cliente'),
        ),
    ]
