# Generated by Django 5.2.7 on 2025-12-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='barrio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='calle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
