# Generated by Django 5.2.7 on 2025-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_plano_archivo_trabajo_created_at_trabajo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
