# Generated by Django 5.2.8 on 2025-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_trabajo_costo_alter_trabajo_descripcion_and_more'),
    ]

    operations = [
        # Quitamos RemoveField porque el campo 'costo' ya no existe
        migrations.AddField(
            model_name='trabajo',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, default=0),
            preserve_default=False,
        ),
    ]
