# Generated by Django 5.2.8 on 2025-12-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_apellido_alter_cliente_barrio_and_more'),
        ('trabajos', '0003_remove_trabajo_costo_trabajo_costo_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabajos.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='trabajos.trabajo')),
            ],
        ),
    ]
