# Generated by Django 5.2.7 on 2025-12-16 00:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajos', '0002_alter_ubicacion_barrio_alter_ubicacion_calle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagada', models.BooleanField(default=False)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_campo', models.PositiveIntegerField(default=0)),
                ('dias_gabinete', models.PositiveIntegerField(default=0)),
                ('costo_personal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_movilidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_viaticos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_desgaste', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_imprevistos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_aportes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_sellado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_copias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_gestoria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('honorarios_minimos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('honorarios_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_gastos_campo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_gastos_gestion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_honorarios', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('porcentaje_impuestos', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='trabajos.trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='presupuesto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='facturacion.presupuesto'),
        ),
    ]
