# Generated by Django 5.2.8 on 2025-12-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='costo_total',
            new_name='monto_total',
        ),
    ]
