# Generated by Django 5.2.8 on 2025-12-01 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_apellido_alter_cliente_barrio_and_more'),
        ('facturacion', '0002_rename_costo_total_factura_monto_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
