# Generated by Django 5.2.8 on 2025-12-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_factura_monto_pagado_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
