# Generated by Django 5.2.8 on 2025-12-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_monto_pagado'),
        ('trabajos', '0003_remove_trabajo_costo_trabajo_costo_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='descripcion',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='trabajo',
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(default='ADEUDA', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo',
            field=models.CharField(default='residencial', max_length=100),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='ubicacion',
            field=models.CharField(default='Sin ubicación', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.trabajo'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='costo_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
