# Generated by Django 5.2.8 on 2025-11-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_activo_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
    ]
