# Generated by Django 5.2.7 on 2025-12-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_apellido_alter_cliente_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuil',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
