# Generated by Django 5.2.7 on 2025-10-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_estado_cliente_activo_remove_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
