# Generated by Django 5.2.7 on 2025-12-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_cuil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cuil',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='razon_social',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('fisica', 'Persona Física'), ('juridica', 'Persona Jurídica')], max_length=10),
        ),
        migrations.CreateModel(
            name='ClienteFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cuil', models.CharField(max_length=13, unique=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientefisico', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientejuridico', to='clientes.cliente')),
            ],
        ),
    ]
