# Generated by Django 5.2.7 on 2025-12-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_ubicacion_alter_cliente_email_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientefisico',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientefisico',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='razon_social',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='barrio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='calle',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='departamento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='numero',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='piso',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='provincia',
            field=models.CharField(max_length=10),
        ),
    ]
